config/routes.rb
Rails.application.routes.draw do
  
  root to: 'customers#index'
  resources :customers
  resources :firmas_flows
  resources :grupo_empresas
  resources :firmas_tipos_documentos
  resources :facturas_detalles, only: [:create, :destroy] #solo puedo crear y eliminar detalle de factura

  resources :facturas do # permisos a metodo para ver pdf subido en un folder
  member do
    get :nueva_fila
  end
end
  resources :productos do # permisos a metodo para ver pdf subido en un folder
  member do
    get :muestra_pdf
  end
end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/firmas_tipos_documento.rb
# == Schema Information
#
# Table name: firmas_tipos_documentos
#
#  id               :integer          not null, primary key
#  grupo_empresa_id :integer
#  nombre           :string
#  descripcion      :text
#  aceptado         :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class FirmasTiposDocumento < ApplicationRecord
	has_many :firmas_flow
	belongs_to :grupo_empresa
	def name
		nombre
	end

end

app/controllers/firmas_tipos_documentos_controller.rb
class FirmasTiposDocumentosController < ApplicationController
  before_action :set_firmas_tipos_documento, only: [:show, :edit, :update, :destroy]

  # GET /firmas_tipos_documentos
  # GET /firmas_tipos_documentos.json
  def index
    @firmas_tipos_documentos = FirmasTiposDocumento.all
  end

  # GET /firmas_tipos_documentos/1
  # GET /firmas_tipos_documentos/1.json
  def show
    @firmas_flow = FirmasFlow.new #muestro el formulario de detalles de la factura en el detalle
    @firmas_flow.firmas_tipos_documentos_id = @firmas_tipos_documento.id #muestro los detalles de esta factura en la tabla
  end

  # GET /firmas_tipos_documentos/new
  def new
    @firmas_tipos_documento = FirmasTiposDocumento.new
  end

  # GET /firmas_tipos_documentos/1/edit
  def edit
  end

  # POST /firmas_tipos_documentos
  # POST /firmas_tipos_documentos.json
  def create
    @firmas_tipos_documento = FirmasTiposDocumento.new(firmas_tipos_documento_params)

    respond_to do |format|
      if @firmas_tipos_documento.save
        format.html { redirect_to @firmas_tipos_documento, notice: 'Firmas tipos documento was successfully created.' }
        format.json { render :show, status: :created, location: @firmas_tipos_documento }
      else
        format.html { render :new }
        format.json { render json: @firmas_tipos_documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firmas_tipos_documentos/1
  # PATCH/PUT /firmas_tipos_documentos/1.json
  def update
    respond_to do |format|
      if @firmas_tipos_documento.update(firmas_tipos_documento_params)
        format.html { redirect_to @firmas_tipos_documento, notice: 'Firmas tipos documento was successfully updated.' }
        format.json { render :show, status: :ok, location: @firmas_tipos_documento }
      else
        format.html { render :edit }
        format.json { render json: @firmas_tipos_documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firmas_tipos_documentos/1
  # DELETE /firmas_tipos_documentos/1.json
  def destroy
    @firmas_tipos_documento.destroy
    respond_to do |format|
      format.html { redirect_to firmas_tipos_documentos_url, notice: 'Firmas tipos documento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firmas_tipos_documento
      @firmas_tipos_documento = FirmasTiposDocumento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firmas_tipos_documento_params
      params.require(:firmas_tipos_documento).permit(:grupo_empresa_id, :nombre, :descripcion, :aceptado)
    end
end

app/helpers/firmas_tipos_documentos_helper.rb
module FirmasTiposDocumentosHelper
end

app/views/firmas_tipos_documentos/_form.html.erb
<%= simple_form_for(@firmas_tipos_documento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :grupo_empresa  %>
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :aceptado %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/firmas_tipos_documentos/edit.html.erb
<h1>Editing Firmas Tipos Documento</h1>

<%= render 'form', firmas_tipos_documento: @firmas_tipos_documento %>

<%= link_to 'Show', @firmas_tipos_documento %> |
<%= link_to 'Back', firmas_tipos_documentos_path %>

app/views/firmas_tipos_documentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firmas Tipos Documentos</h1>

<table>
  <thead>
    <tr>
      <th>Grupo empresa</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Aceptado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firmas_tipos_documentos.each do |firmas_tipos_documento| %>
      <tr>
        <td><%= firmas_tipos_documento.grupo_empresa_id %></td>
        <td><%= firmas_tipos_documento.nombre %></td>
        <td><%= firmas_tipos_documento.descripcion %></td>
        <td><%= firmas_tipos_documento.aceptado %></td>
        <td><%= link_to 'Show', firmas_tipos_documento %></td>
        <td><%= link_to 'Edit', edit_firmas_tipos_documento_path(firmas_tipos_documento) %></td>
        <td><%= link_to 'Destroy', firmas_tipos_documento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firmas Tipos Documento', new_firmas_tipos_documento_path %>

app/views/firmas_tipos_documentos/new.html.erb
<h1>New Firmas Tipos Documento</h1>

<%= render 'form', firmas_tipos_documento: @firmas_tipos_documento %>

<%= link_to 'Back', firmas_tipos_documentos_path %>

app/views/firmas_tipos_documentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grupo empresa:</strong>
  <%= @firmas_tipos_documento.grupo_empresa_id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @firmas_tipos_documento.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @firmas_tipos_documento.descripcion %>
</p>

<p>
  <strong>Aceptado:</strong>
  <%= @firmas_tipos_documento.aceptado %>
</p>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Firmas tipos documentos</th>
      <th>Lleva firma</th>
      <th>Tipo</th>
      <th>Paso aceptado</th>
      <th>Texto aceptado</th>
      <th>Paso no aceptado</th>
      <th>Texto no aceptado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firmas_tipos_documentos.firmas_flows.each do |firmas_flow| %>
      <tr>
        <td><%= firmas_flow.user_id %></td>
        <td><%= firmas_flow.firmas_tipos_documentos_id %></td>
        <td><%= firmas_flow.lleva_firma %></td>
        <td><%= firmas_flow.tipo %></td>
        <td><%= firmas_flow.paso_aceptado %></td>
        <td><%= firmas_flow.texto_aceptado %></td>
        <td><%= firmas_flow.paso_no_aceptado %></td>
        <td><%= firmas_flow.texto_no_aceptado %></td>
        <td><%= link_to 'Show', firmas_flow %></td>
        <td><%= link_to 'Edit', edit_firmas_flow_path(firmas_flow) %></td>
        <td><%= link_to 'Destroy', firmas_flow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_firmas_tipos_documento_path(@firmas_tipos_documento) %> |
<%= link_to 'Back', firmas_tipos_documentos_path %>