config/routes.rb
Rails.application.routes.draw do
  
  root to: 'customers#index'
  resources :customers
  resources :firmas_flows
  resources :grupo_empresas
  resources :firmas_tipos_documentos
  resources :facturas_detalles, only: [:create, :destroy] #solo puedo crear y eliminar detalle de factura

  resources :facturas do # permisos a metodo para ver pdf subido en un folder
  member do
    get :nueva_fila
  end
end
  resources :productos do # permisos a metodo para ver pdf subido en un folder
  member do
    get :muestra_pdf
  end
end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/factura.rb
# == Schema Information
#
# Table name: facturas
#
#  id             :integer          not null, primary key
#  numero         :integer
#  fecha          :date
#  nit_cliente    :string
#  nombre_cliente :string
#  total          :decimal(, )
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Factura < ApplicationRecord
	validates_presence_of :numero, :fecha, :nit_cliente, :nombre_cliente # validacion para requeir valores
	validates_uniqueness_of :numero # validacion sin repetir
	validates_length_of :nombre_cliente, within: 3..255 #validacion de largo requerido permitido
	has_many :facturas_detalles # tiene muchos en plural 


   def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |factura|
        csv << factura.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
     respond_to do |format|
      format.html
      format.csv { render text: @facturas.to_csv }
      format.xls { render text: @facturas.to_csv(col_sep: "\t") }
    end
  end


  def nueva_fila
    #validar primero si el archivo @producto.url_pdf existe
    send_file @factura.nueva_fila
  end


   def excel
    #validar primero si el archivo @producto.url_pdf existe

  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
    @factura_detalle = FacturaDetalle.new #muestro el formulario de detalles de la factura en el detalle
    @factura_detalle.factura_id = @factura.id #muestro los detalles de esta factura en la tabla
    @detfactura = FacturaDetalle.where("factura_id = ?",params[:id])
    respond_to do |format|
      format.html
      format.js
      format.csv { render text: @detfactura.to_csv }
      format.xls { render text: @detfactura.to_csv(col_sep: "\t") }
      format.pdf  {render template: 'facturas/reporte', pdf: 'Reporte'}
    end

    
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
  end

  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(factura_params)#creo variable  nueva con los parametros
    @factura.total=0 #al crear nueva factura establezco por default 0

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Factura creada exitosamente.' }
        format.json { render :show, status: :created, location: @factura }
      else
        format.html { render :new }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { render :show, status: :ok, location: @factura }
      else
        format.html { render :edit }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to facturas_url, notice: 'Factura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:numero, :fecha, :nit_cliente, :nombre_cliente, :total)
    end
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_form.html.erb
<%= simple_form_for(@factura) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :numero %>
    <%= f.input :fecha %>
    <%= f.input :nit_cliente %>
    <%= f.input :nombre_cliente %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/facturas/edit.html.erb
<h1>Editing Factura</h1>

<%= render 'form', factura: @factura %>

<%= link_to 'Show', @factura %> |
<%= link_to 'Back', facturas_path %>

app/views/facturas/fila_nueva.html.erb
 	<tr >
        <td><%= factura_detalle.factura_id %></td>
        <td><%= factura_detalle.producto.nombre %></td>
        <td><%= factura_detalle.cantidad %></td>
        <td><%= factura_detalle.precio %></td>
        <td><%= factura_detalle.total %></td>
        <td><%= link_to 'Show', factura_detalle %></td>
        <td><%= link_to 'Edit', edit_factura_detalle_path(factura_detalle) %></td>
        <td><%= link_to 'Destroy', factura_detalle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/facturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facturas</h1>
<div class="table responsive">
<table class="table table-bordered table-striped table-hover" id='facturas'>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Fecha</th>
      <th>Nit cliente</th>
      <th>Nombre cliente</th>
      <th>Total</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @facturas.each do |factura| %>
      <tr>
        <td><%= factura.numero %></td>
        <td><%= factura.fecha %></td>
        <td><%= factura.nit_cliente %></td>
        <td><%= factura.nombre_cliente %></td>
        <td><%= factura.total %></td>
        <td>
        <%= link_to 'Ver detalle', factura, class: 'btn btn-default fa fa-eye' %>
        <%= link_to 'Destroy', factura, class: 'btn btn-danger fa fa-close', method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#facturas').DataTable();
});
</script>

<br>

<%= link_to 'New Factura', new_factura_path %>

app/views/facturas/new.html.erb
<h1>New Factura</h1>

<%= render 'form', factura: @factura %>

<%= link_to 'Back', facturas_path %>

app/views/facturas/reporte.pdf.erb
 <!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<%= wicked_pdf_stylesheet_link_tag 'pdf' %>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<meta charset="utf-8">
</head>
<body>
<h1 align="center"> FACTURA NO <%= @factura.numero %> </h1>
  <div class="row">
    <div class="col-sm-2">
      <h4>
      <strong>Factura No: <%= @factura.numero %></strong>
      </h4>
    </div>
    <div class="col-sm-2">
    <h4>
      <strong>Nit: <%= @factura.nit_cliente %></strong>
    </h4>
    </div>
    <div class="col-sm-2">
    <h4>
      <strong>Nombre: <%= @factura.nombre_cliente %></strong>
    </h4>
    </div>
    <div class="col-sm-1">
    <h4>
      <strong><%= @factura.fecha %></strong>
    </h4>
    </div>
  </div>
<br>
	<table class="table table-bordered">
	<thead>
	<tr>
	  <th>Producto</th>
    <th>Cantidad</th>
    <th>Precio</th>
    <th>Total</th>
	</tr>
	</thead>

	<tbody>
    <% @factura.facturas_detalles.each do |factura_detalle| %>
      <tr>
            <td><%= factura_detalle.producto.descripcion if factura_detalle.producto %></td>
            <td><%= factura_detalle.cantidad %></td>
            <td><%= factura_detalle.precio %></td>
            <td><%= factura_detalle.total %></td>
       

      </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td>Total:</td>
        <td><strong id="total"> <%= @factura.total %></strong></td>

      </tr>
    
    </tbody>
	</table>
   
</body>
</html> 

app/views/facturas/show.html.erb
<div class="container">
<div class="row">
<div class="col-sm-2"> </div>
<div class="col-sm-8">
<p id="notice"><%= notice %></p>
<div id="error" class="hidden">Nuevo Producto agregado exitosamente a la factura</div>
<div class="container">

<div class="row">

<div class="col-sm-2">
  <h4>
  <strong>Factura No: <%= @factura.numero %></strong>

  
  </h4>
</div>

<div class="col-sm-2">
<h4>
  <strong>Nit: <%= @factura.nit_cliente %></strong>
</h4>
</div>
<div class="col-sm-2">
<h4>
  <strong>Nombre: <%= @factura.nombre_cliente %></strong>
  
</h4>
</div>

<div class="col-sm-1">
<h4>
  <strong><%= @factura.fecha %></strong>
</h4>
</div>
</div>
</div>

<hr>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Detalle de la Factura</h4> <!-- COPIO LA TABLA DEL DETALLE FACTURA --></div>
  <div class="panel-body">
    
    <table class="table table-bordered table-hover table-striped table-condenced" id="detalle">
      <thead>
        <tr>
          
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Precio</th>
          <th>Total</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @factura.facturas_detalles.each do |factura_detalle| %>

          <tr id="detalle_fila_<%=factura_detalle.id %>">
            
            <td><%= factura_detalle.producto.descripcion if factura_detalle.producto %></td>
            <td><%= factura_detalle.cantidad %></td>
            <td><%= factura_detalle.precio %></td>
            <td><%= factura_detalle.total %></td>
            <td><%= link_to 'Eliminar',  factura_detalle, remote: true, :method => :delete, data: {confirm: "Desea eliminar el detalle de : #{factura_detalle.producto.descripcion} #{factura_detalle.precio}"}, class: 'btn btn-danger fa fa-close' %></td>

          </tr>

        <% end %>
        <%= render '/facturas_detalles/form', factura_detalle: @factura_detalle %> <!-- RENDERISO EL FORMUULARIO DETALLE FACTURA -->
       
         
      </tbody>
    </table>
        <div class="row">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
            <h4>Total:
            <strong id="total"> <%= @factura.total %></strong>
            </h4>
        </div>
        </div>
            
     
  </div>
</div>


<h4 align="right">
  
  <a href="<%= @factura.id %>.xls" class="btn btn-success">  <span class="fa fa-file-excel-o"></span> <strong>GENERAR EXCEL </strong> </a>
  <a href="<%= @factura.id %>.pdf" class="btn btn-danger">  <span class="fa fa-file-pdf-o"></span> <strong>GENERAR PDF </strong> </a>
  
</h4>


<%= link_to 'Edit', edit_factura_path(@factura) %> |
<%= link_to 'Back', facturas_path %>
</div>
<div class="col-sm-2"></div>
</div>
</div>