config/routes.rb
Rails.application.routes.draw do
  
  root to: 'customers#index'
  resources :customers
  resources :firmas_flows
  resources :grupo_empresas
  resources :firmas_tipos_documentos
  resources :facturas_detalles, only: [:create, :destroy] #solo puedo crear y eliminar detalle de factura

  resources :facturas do # permisos a metodo para ver pdf subido en un folder
  member do
    get :nueva_fila
  end
end
  resources :productos do # permisos a metodo para ver pdf subido en un folder
  member do
    get :muestra_pdf
  end
end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/firmas_flow.rb
# == Schema Information
#
# Table name: firmas_flows
#
#  id                         :integer          not null, primary key
#  user_id                    :integer
#  firmas_tipos_documentos_id :integer
#  lleva_firma                :boolean
#  tipo                       :string
#  paso_aceptado              :integer
#  texto_aceptado             :string
#  paso_no_aceptado           :integer
#  texto_no_aceptado          :string
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#

class FirmasFlow < ApplicationRecord
	belongs_to :user
	belongs_to :firmas_tipos_documento

end

app/controllers/firmas_flows_controller.rb
class FirmasFlowsController < ApplicationController
  before_action :set_firmas_flow, only: [:show, :edit, :update, :destroy]

  # GET /firmas_flows
  # GET /firmas_flows.json
  def index
    @firmas_flows = FirmasFlow.all
  end

  # GET /firmas_flows/1
  # GET /firmas_flows/1.json
  def show
  end

  # GET /firmas_flows/new
  def new
    @firmas_flow = FirmasFlow.new
  end

  # GET /firmas_flows/1/edit
  def edit
  end

  # POST /firmas_flows
  # POST /firmas_flows.json
  def create
    @firmas_flow = FirmasFlow.new(firmas_flow_params)

    respond_to do |format|
      if @firmas_flow.save
        format.html { redirect_to @firmas_flow, notice: 'Firmas flow was successfully created.' }
        format.json { render :show, status: :created, location: @firmas_flow }
      else
        format.html { render :new }
        format.json { render json: @firmas_flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firmas_flows/1
  # PATCH/PUT /firmas_flows/1.json
  def update
    respond_to do |format|
      if @firmas_flow.update(firmas_flow_params)
        format.html { redirect_to @firmas_flow, notice: 'Firmas flow was successfully updated.' }
        format.json { render :show, status: :ok, location: @firmas_flow }
      else
        format.html { render :edit }
        format.json { render json: @firmas_flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firmas_flows/1
  # DELETE /firmas_flows/1.json
  def destroy
    @firmas_flow.destroy
    respond_to do |format|
      format.html { redirect_to firmas_flows_url, notice: 'Firmas flow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firmas_flow
      @firmas_flow = FirmasFlow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firmas_flow_params
      params.require(:firmas_flow).permit(:user_id, :firmas_tipos_documentos_id, :lleva_firma, :tipo, :paso_aceptado, :texto_aceptado, :paso_no_aceptado, :texto_no_aceptado)
    end
end

app/helpers/firmas_flows_helper.rb
module FirmasFlowsHelper
end

app/views/firmas_flows/_form.html.erb
<%= simple_form_for(@firmas_flow) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
     <%= f.association :user  %>
    <%= f.input :firmas_tipos_documentos_id %>
    <%= f.association :firmas_tipos_documento %>
    <%= f.input :lleva_firma %>
    <%= f.input :tipo %>
    <%= f.input :paso_aceptado %>
    <%= f.input :texto_aceptado %>
    <%= f.input :paso_no_aceptado %>
    <%= f.input :texto_no_aceptado %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/firmas_flows/edit.html.erb
<h1>Editing Firmas Flow</h1>

<%= render 'form', firmas_flow: @firmas_flow %>

<%= link_to 'Show', @firmas_flow %> |
<%= link_to 'Back', firmas_flows_path %>

app/views/firmas_flows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firmas Flows</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Firmas tipos documentos</th>
      <th>Lleva firma</th>
      <th>Tipo</th>
      <th>Paso aceptado</th>
      <th>Texto aceptado</th>
      <th>Paso no aceptado</th>
      <th>Texto no aceptado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firmas_flows.each do |firmas_flow| %>
      <tr>
        <td><%= firmas_flow.user_id %></td>
        <td><%= firmas_flow.firmas_tipos_documentos_id %></td>
        <td><%= firmas_flow.lleva_firma %></td>
        <td><%= firmas_flow.tipo %></td>
        <td><%= firmas_flow.paso_aceptado %></td>
        <td><%= firmas_flow.texto_aceptado %></td>
        <td><%= firmas_flow.paso_no_aceptado %></td>
        <td><%= firmas_flow.texto_no_aceptado %></td>
        <td><%= link_to 'Show', firmas_flow %></td>
        <td><%= link_to 'Edit', edit_firmas_flow_path(firmas_flow) %></td>
        <td><%= link_to 'Destroy', firmas_flow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firmas Flow', new_firmas_flow_path %>

app/views/firmas_flows/new.html.erb
<h1>New Firmas Flow</h1>

<%= render 'form', firmas_flow: @firmas_flow %>

<%= link_to 'Back', firmas_flows_path %>

app/views/firmas_flows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @firmas_flow.user_id %>
</p>

<p>
  <strong>Firmas tipos documentos:</strong>
  <%= @firmas_flow.firmas_tipos_documentos_id %>
</p>

<p>
  <strong>Lleva firma:</strong>
  <%= @firmas_flow.lleva_firma %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @firmas_flow.tipo %>
</p>

<p>
  <strong>Paso aceptado:</strong>
  <%= @firmas_flow.paso_aceptado %>
</p>

<p>
  <strong>Texto aceptado:</strong>
  <%= @firmas_flow.texto_aceptado %>
</p>

<p>
  <strong>Paso no aceptado:</strong>
  <%= @firmas_flow.paso_no_aceptado %>
</p>

<p>
  <strong>Texto no aceptado:</strong>
  <%= @firmas_flow.texto_no_aceptado %>
</p>

<%= link_to 'Edit', edit_firmas_flow_path(@firmas_flow) %> |
<%= link_to 'Back', firmas_flows_path %>