config/routes.rb
Rails.application.routes.draw do
  
  root to: 'customers#index'
  resources :customers
  resources :firmas_flows
  resources :grupo_empresas
  resources :firmas_tipos_documentos
  resources :facturas_detalles, only: [:create, :destroy] #solo puedo crear y eliminar detalle de factura

  resources :facturas do # permisos a metodo para ver pdf subido en un folder
  member do
    get :nueva_fila
  end
end
  resources :productos do # permisos a metodo para ver pdf subido en un folder
  member do
    get :muestra_pdf
  end
end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/producto.rb
# == Schema Information
#
# Table name: productos
#
#  id                  :integer          not null, primary key
#  codigo              :string
#  descripcion         :string
#  precio              :decimal(, )
#  observaciones       :text
#  activo              :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  imagen_file_name    :string
#  imagen_content_type :string
#  imagen_file_size    :integer
#  imagen_updated_at   :datetime
#  pdf_file_name       :string
#  pdf_content_type    :string
#  pdf_file_size       :integer
#  pdf_updated_at      :datetime
#

class Producto < ApplicationRecord
	validates :codigo, uniqueness: true
	validates :codigo, :descripcion, :precio, presence: true
	has_attached_file :imagen, styles: { medium: "300x300", thumb: "100x100" }, default_url: "/images/no-existe.png"
  	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/

  	has_attached_file :pdf, default_url: "/images/no-existe.png", path: ":rails_root/pdf/:id/:filename",   url: ":rails_root/pdf/:id/:filename"

    validates_attachment_content_type :pdf, content_type: ['application/pdf']            	

    def url_pdf
    	 Rails.root.join("pdf/",self.id.to_s,self.pdf_file_name||="nofile.pdf").to_s#agregarmos la ruta url con el nombre dle archivo
    end
    def name
		descripcion
	 end

   def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |producto|
        csv << producto.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_producto, only: [:show, :edit, :update, :destroy, :muestra_pdf]

  # GET /productos
  # GET /productos.json
  def index
    #@productos = Producto.paginate(:page=>params[:page], :per_page => 10)
    @productos = Producto.all
    respond_to do |format|
      format.html
      format.js
      format.pdf  {render template: 'productos/reporte', pdf: 'Reporte'}
    end
  end


  def muestra_pdf
    #validar primero si el archivo @producto.url_pdf existe
    send_file @producto.url_pdf, type: 'application/pdf', disposition: 'inline' #llama al controlador para enviar archivo
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:codigo, :descripcion, :precio, :observaciones, :activo, :imagen, :pdf)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= simple_form_for(@producto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :codigo %>
    <%= f.input :descripcion %>
    <%= f.input :precio %>
    <%= f.input :observaciones %>
    <%= f.input :activo %>
    <%= f.input :imagen, as: :file %>
    <%= f.input :pdf, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1 align="center">Productos</h1>
<center>
<%= link_to 'Nuevo producto', new_producto_path, class: 'btn btn-primary fa fa-plus', title: 'Agregar nuevo producto' %> 
<a href="/productos.xls" class="btn btn-success fa fa-file-excel-o" title="generar un excel"> Excel </a>
</center>
<br>
<div class="table-responsive">
<table class="table table-hover table-bordered" id="myTable">
  <thead>
    <tr>
      <th><strong><center>Imagen</strong></center></th>
      <th><strong><center>Codigo</strong></center></th>
      <th><strong><center>Descripcion</strong></center></th>
      <th><strong><center>Precio</strong></center></th>
      <th><strong><center>Observaciones</strong></center></th>
      <th><strong><center>Activo</strong></center></th>
      <th><strong><center>Catalogo</strong></center></th>
      <th><strong><center>Opciones </strong></center></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><img src="<%= producto.imagen %>" width="50" height="50" title="imagen del producto"></td>
        <td><%= producto.codigo %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.observaciones %></td>
        <% if producto.activo == true %>
          <td> ACTIVO</td>
        <% else %>
          <td>INACTIVO</td>
        <% end %>
        <td> <%= link_to 'Descargar', muestra_pdf_producto_path(producto) , class: 'btn btn-primary fa fa-download', title: 'Descargar detalles del producto' %> </td>
        <td><%= link_to 'Detalles', producto, class: 'btn btn-default fa fa-eye', title: 'ver los detalles del producto' %>
        <%= link_to 'Editar', edit_producto_path(producto) , class: 'btn btn-warning fa fa-edit',title: 'editar el producto' %>
        <%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Esta seguro?' } , class: 'btn btn-danger fa fa-close', title: 'Eliminar el producto' %>
        
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>

app/views/productos/reporte.pdf.erb
 <!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<%= wicked_pdf_stylesheet_link_tag 'pdf' %>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<meta charset="utf-8">
</head>
<body>
<h1 align="center"> PRODUCTOS DISPONIBLES </h1>
	<table class="table table-bordered">
	<thead>
	<tr>
		<th>imagen</th>
		<th>codigo</th>
		<th>descripcion</th>
		<th>precio</th>
		<th>observaciones</th>
		<th>estado</th>
		
	</tr>
	</thead>

	<tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><img src="<%= producto.imagen %>"></td>
        <td><%= producto.codigo %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.observaciones %></td>
        <% if producto.activo == true %>
          <td> ACTIVO</td>
        <% else %>
          <td>INACTIVO</td>
        <% end %>

      </tr>
    <% end %>
    </tbody>
	</table>
</body>
</html> 

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @producto.codigo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @producto.observaciones %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @producto.activo %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>